# July 20th

## functions : reusable parts of code

```python
# function definition
def function_name(parameters):
    body of the function

# function call
function_name(parameters)

```

In [3]:
def add(a, b):
    tot = a + b
    print(tot)

add(2, 4)

6


### Argument Matching 
- Positional
- Keyword

In [221]:
def example(first, second):
    print(f'first: {first}')
    print(f'Scnd : {second}')

In [223]:
example("One", "Two") # positional matching

first: One
Scnd : Two


In [225]:
example("Two", "One") # positional matching

first: Two
Scnd : One


In [227]:
example(second = 'Two', first = "One") # keyword matching

first: One
Scnd : Two


In [237]:
def welcome_message(name, greeting):
    print(f"Welcome {name}, {greeting}.")

In [239]:
welcome_message('Happy to have you', 'Alan')

Welcome Happy to have you, Alan.


In [241]:
welcome_message(greeting = 'Happy to have you', name = 'Alan')

Welcome Alan, Happy to have you.


In [243]:
welcome_message('Alan')

TypeError: welcome_message() missing 1 required positional argument: 'greeting'

### default values 

In [6]:
def welcome_message_with_default(name, greeting= 'happy to have you!'):
    print(f"Welcome {name}, {greeting}")

In [8]:
welcome_message_with_default('Alan')

Welcome Alan, happy to have you!


In [10]:
welcome_message_with_default('Alan', 'its our honour to have you here')

Welcome Alan, its our honour to have you here


---

**the default value will be picked when a value is not passed for that parameter**

---

## - Scope of data 

In [16]:
def add(a, b):
    tot = a + b
    print(tot)

add(2, 4)

6


In [18]:
print(tot)

NameError: name 'tot' is not defined

#### tot - local scope to the function 

- Global Scope: any variable/ function defined outside a function or class (anywhere in the kernel) is global scope.
- Local Scope : any variable/function defined inside a function or a class is local to that funtion or class.

In [23]:
def add(a, b):
    tot = a + b
    print(tot)

# a, b and tot are local to the function add

In [25]:
x = 100

def add(a,b):
    tot = (a + b) * x
    print(tot)

# since x is not defined in the function, hence global will be taken up

In [27]:
add(2,3)

500


---
<b>
there can same variable names for local as well as global scope, preference will be given to the envireonment from where they have been called
</b>

---

In [32]:
x = 100 # global
def add(a,b):
    x = 0.1  # local
    tot = (a + b) * x
    print(tot)

In [34]:
add(2,3)

0.5


In [36]:
print(x)

100


In [50]:
def calculate_painting_area(length, width, height):
    total_wall_area = (length + width ) * height
    return total_wall_area

In [54]:
area = calculate_painting_area(15, 12, 10)

In [56]:
total_wall_area

NameError: name 'total_wall_area' is not defined

In [58]:
area

270

In [66]:
def calculate_painting_cost(area, type_of_paint):
    if type_of_paint == 'standard':
        material_cost = 12
        labor_cost = 8
    elif type_of_paint == 'premium':
        material_cost = 18
        labor_cost = 12
    elif type_of_paint == 'luxury':
        material_cost = 25
        labor_cost = 18
    else:
        print('Invalid paint type')
        material_cost = -9999
        labor_cost = -9999
    return (material_cost +labor_cost) * area
        

In [68]:
calculate_painting_cost(area, 'premium')

8100

## Modules vs  Package vs Libraries

- modules are any **.py** extension files
- package directory containing modules/collection of modules
- library is a collection of modules performing specific task

In [74]:
# what are modules and packages and libraries available : 

In [ ]:
help("modules")

In [ ]:
# to install new modules 

## import statement
- Search for the module
1. Current directory
2. Standard library path
3. any other  path 

In [79]:
import sys

for i,p in enumerate(sys.path):
    print(f"{i}. {p}")

0. /Users/learnersgalaxy/Library/CloudStorage/OneDrive-Personal/Emeritus/IITG-DSBA March 27th/Python
1. /opt/anaconda3/lib/python312.zip
2. /opt/anaconda3/lib/python3.12
3. /opt/anaconda3/lib/python3.12/lib-dynload
4. 
5. /opt/anaconda3/lib/python3.12/site-packages
6. /opt/anaconda3/lib/python3.12/site-packages/aeosa


In [83]:
list(enumerate(['a', 'b', 'c']))

[(0, 'a'), (1, 'b'), (2, 'c')]

```python

import package-name
```
**Search for the package and create an instance in present kernel with the same name.**

In [86]:
import math

In [88]:
print(dir(math))

['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'sumprod', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [90]:
math.log10(20)

1.3010299956639813

```python
import package-name as alias
```
**Search for the package and create an instance in present kernel with the alias name.**

In [96]:
import string as strn

In [98]:
print(dir(string))

NameError: name 'string' is not defined

In [100]:
print(dir(strn))

['Formatter', 'Template', '_ChainMap', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_re', '_sentinel_dict', '_string', 'ascii_letters', 'ascii_lowercase', 'ascii_uppercase', 'capwords', 'digits', 'hexdigits', 'octdigits', 'printable', 'punctuation', 'whitespace']


In [102]:
strn.capwords('hello people')

'Hello People'

In [104]:
strn.digits

'0123456789'

In [106]:
strn.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

``` python

from package-name import specific functions or data attributes
```

**Searches for the package and gets only the specific function or data attributes and creates its instance inthe present runtime**

In [110]:
from string import punctuation

In [114]:
punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [117]:
from string import punctuation as punc, digits as dg

In [121]:
punc

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [123]:
dg

'0123456789'

In [127]:
import mymodule

Welcome to mymodule


# NumPy: Numerical Python
1. Array creation and storage and all functions 
2. Laplace, Fourier Advance maths and linear algebra
3. Random Numbers 

## Arrays: 1 to n dimensional homogenous data strucntures

In [131]:
import numpy as np

In [135]:
temp = [120, 100, 110,98, 102, 95, 80, 75]

$C = (F - 32) * \frac{5}{9}$

In [138]:
temp_C = [round((F- 32) * (5/9),2) for F in temp]
print(temp_C)

[48.89, 37.78, 43.33, 36.67, 38.89, 35.0, 26.67, 23.89]


In [ ]:
# 1 dimensional 

In [133]:
temp_array = np.array([120, 100, 110,98, 102, 95, 80, 75])

In [144]:
((temp_array - 32)* (5/9)).round(2)

array([48.89, 37.78, 43.33, 36.67, 38.89, 35.  , 26.67, 23.89])

str > float > int

In [147]:
np.array([2, '23', 67.09, True])

array(['2', '23', '67.09', 'True'], dtype='<U32')

In [149]:
np.array([2, '23', 67.09, True], dtype = int )

array([ 2, 23, 67,  1])

### 2 dimensional array

### Side note - Random number generation


In [162]:
np.random.randint(50, 120, (5,6) )

array([[ 65,  65,  71,  70, 105,  96],
       [113,  63, 103,  79,  83,  80],
       [ 96,  53,  82,  63,  92,  54],
       [ 82,  82, 106, 114, 103, 113],
       [112, 118,  75,  59, 103, 107]])

In [166]:
temps_fahrenheit = np.array([[85, 87, 84, 82, 86, 88],     
                             [90, 91, 89, 88, 92, 93],     
                             [78, 80, 79, 77, 81, 83],     
                             [95, 96, 94, 93, 97, 98],     
                             [88, 89, 87, 86, 90, 91]])

In [168]:
# properties of array 
print("No. of dimensions : ", temps_fahrenheit.ndim)
print("Shape of the array: ", temps_fahrenheit.shape)
print("Size of the array : ", temps_fahrenheit.size)
print("Dtype of the array: ", temps_fahrenheit.dtype)

No. of dimensions :  2
Shape of the array:  (5, 6)
Size of the array :  30
Dtype of the array:  int64


### add data for the 7th day 

### -- stack
hstack : concatenates 2 arrays increasing the columns
vstack : concatenates 2 arrays increasing the rows

In [186]:
## add data for the 7th day 
day7 = np.array([[89], [94], [82], [99], [92]])
print(day7.shape)

(5, 1)


In [180]:
np.hstack((temps_fahrenheit, day7))

array([[85, 87, 84, 82, 86, 88, 89],
       [90, 91, 89, 88, 92, 93, 94],
       [78, 80, 79, 77, 81, 83, 82],
       [95, 96, 94, 93, 97, 98, 99],
       [88, 89, 87, 86, 90, 91, 92]])

### access elements :

In [ ]:
temp_array[[2, 5, 1]]

array([110,  95, 100])

In [194]:
# for 1 value
temps_fahrenheit[3, 4]

97

In [196]:
temps_fahrenheit

array([[85, 87, 84, 82, 86, 88],
       [90, 91, 89, 88, 92, 93],
       [78, 80, 79, 77, 81, 83],
       [95, 96, 94, 93, 97, 98],
       [88, 89, 87, 86, 90, 91]])

In [198]:
# for a complete row: 
temps_fahrenheit[2]

array([78, 80, 79, 77, 81, 83])

In [202]:
# for a complete col: 
temps_fahrenheit[:, 3] # 1 d

array([82, 88, 77, 93, 86])

In [206]:
# for a complete col: 
temps_fahrenheit[:, [3]] # 2d

array([[82],
       [88],
       [77],
       [93],
       [86]])